blank_issues_enabled: false
contact_links:
  - name: "GitHub CLI issues"
    url: https://github.com/cli/cli/issues/new/choose
    about: "Go to the upstream repository for anything unrelated to the snap packaging"
