name: gh
summary: The GitHub CLI
description: https://cli.github.com
adopt-info: gh
grade: stable
confinement: devmode  # classic
base: core18
license: MIT
package-management:  # snap refresh snapcraft --channel=edge/pr-2911
  repositories:
    - source: ppa:longsleep/golang-backports
parts:
  gh:
    plugin: make
    artifacts:
    - bin/gh
    source: .
    build-packages:
    - golang-go
    - git
    stage-packages:
    - golang-go
    - git
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version `git describe --tags 2>/dev/null || git rev-parse --short HEAD`
    override-build: |
      LDFLAGS='' make -j2
      cp bin/gh $SNAPCRAFT_PART_INSTALL/
apps:
  gh:
    command: gh
