name: gh
summary: The GitHub CLI
description: |
  https://cli.github.com

  **`gh` - The GitHub CLI tool**

  `gh` is GitHub on the command line, and it's now available in beta. It brings pull requests, issues, and other GitHub concepts to
  the terminal next to where you are already working with `git` and your code.

  _Usage_

  - `gh pr [status, list, view, checkout, create]`
  - `gh issue [status, list, view, create]`
  - `gh help`
adopt-info: gh
grade: stable
confinement: strict  # classic
base: core18
license: MIT
parts:
  gh:
    plugin: make
    source: .
    build-snaps:
    - go
    - snapd
    build-packages:
    - git
    stage-packages:
    - git
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version `(git describe --tags | sed 's/^v//') 2>/dev/null || git rev-parse --short HEAD`
    override-build: |
      LDFLAGS='' make -j2
      cp bin/gh $SNAPCRAFT_PART_INSTALL/
      bin/gh completion -s bash > $SNAPCRAFT_PART_INSTALL/completion.sh
apps:
  gh:
    command: gh
    plugs:
    - home
    - network
    completer: completion.sh
