name: gh
summary: The GitHub CLI
description: https://cli.github.com
adopt-info: gh
grade: stable
confinement: strict  # classic
base: core18
license: MIT
package-management:  # snap refresh snapcraft --channel=edge/pr-2911
  repositories:
    - source: ppa:longsleep/golang-backports
parts:
  gh:
    plugin: make
    source: .
    build-packages:
    - golang-go
    - git
    stage-packages:
    - golang-go
    - git
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version `(git describe --tags | sed 's/^v//') 2>/dev/null || git rev-parse --short HEAD`
    override-build: |
      LDFLAGS='' make -j2
      cp bin/gh $SNAPCRAFT_PART_INSTALL/
      bin/gh completion -s bash > $SNAPCRAFT_PART_INSTALL/completion.sh
apps:
  gh:
    command: gh
    plugs:
    - home
    - network
    completer: completion.sh
